/**
 * Generate tests/fixtures/golden-gable-roof.obj — a synthetic gable roof with
 * ANALYTICALLY EXACT geometry, finely tessellated so it exercises the real
 * mesh-extraction segmentation path (which grows facets through spatially
 * adjacent sub-metre triangles, like a true ODM mesh).
 *
 * Run: node --experimental-strip-types scripts/gen-golden-roof.ts
 *
 * Building footprint 12 m (X) x 8 m (Y). Ridge along X at Y=4. Eave top z=3,
 * ridge z=5 -> half-width run 4 m, rise 2 m -> pitch 6/12 (slope atan(0.5)).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const NX = 24; // 0.5 m cells along the 12 m ridge
const NY = 8; //  0.5 m cells along each 4 m slope

const verts: [number, number, number][] = [];
const faces: number[][] = [];
const idx = (x: number, y: number, z: number) => {
  verts.push([x, y, z]);
  return verts.length; // OBJ is 1-based
};

// One sloped plane as an NX x NY grid of quads. `zAt` gives the ridge-linear height.
function addPlane(y0: number, y1: number, zAt: (y: number) => number) {
  const grid: number[][] = [];
  for (let i = 0; i <= NX; i++) {
    const row: number[] = [];
    const x = (i / NX) * 12;
    for (let j = 0; j <= NY; j++) {
      const y = y0 + (j / NY) * (y1 - y0);
      row.push(idx(x, y, zAt(y)));
    }
    grid.push(row);
  }
  for (let i = 0; i < NX; i++) {
    for (let j = 0; j < NY; j++) {
      faces.push([grid[i][j], grid[i + 1][j], grid[i + 1][j + 1], grid[i][j + 1]]);
    }
  }
}

addPlane(0, 4, (y) => 3 + 0.5 * y); // south plane: z 3 -> 5
addPlane(8, 4, (y) => 7 - 0.5 * y); // north plane: z 3 -> 5

// Vertical walls (slope 90 deg -> discarded by the extractor as non-roof).
const w = (a: [number, number, number], b: [number, number, number], c: [number, number, number], d: [number, number, number]) =>
  faces.push([idx(...a), idx(...b), idx(...c), idx(...d)]);
w([0, 0, 0], [12, 0, 0], [12, 0, 3], [0, 0, 3]); // south
w([0, 8, 0], [12, 8, 0], [12, 8, 3], [0, 8, 3]); // north
w([0, 0, 0], [0, 0, 3], [0, 4, 5], [0, 8, 3]); // gable end x=0 (partial)
w([12, 0, 0], [12, 0, 3], [12, 4, 5], [12, 8, 3]); // gable end x=12 (partial)

const lines = [
  "# GENERATED by scripts/gen-golden-roof.ts — do not edit by hand.",
  "# Synthetic 12x8 m gable roof, 6/12 pitch, z-up, metres. Ground truth:",
  "#   facetCount=2  pitch=6/12 (26.565 deg)",
  "#   total surface=107.331 m^2=1155.3 sqft (roofSquares~=11.55)  projected=96 m^2=1033.3 sqft",
  ...verts.map(([x, y, z]) => `v ${x} ${y} ${z}`),
  ...faces.map((f) => `f ${f.join(" ")}`),
  "",
];

const out = fileURLToPath(new URL("../tests/fixtures/golden-gable-roof.obj", import.meta.url));
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}: ${verts.length} verts, ${faces.length} faces`);
