/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx/theme.ts
 * Command: astryx theme build lib/astryx/theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/**
 * aernova theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { aernovaTheme } from './aernova';
 *   import './aernova.css';
 */
export const aernovaTheme = {
  name: 'aernova',
  __built: true,
  tokens: {
    "--font-family-body": "\"-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif\"",
    "--font-family-heading": "\"-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif\"",
    "--color-accent": "light-dark(oklch(21% 0.04 265), #ffffff)",
    "--color-on-accent": "light-dark(oklch(95.5% 0.01 255), oklch(12.5% 0.05 264))",
    "--color-background-body": "light-dark(oklch(95.5% 0.01 255), oklch(12.5% 0.05 264))",
    "--color-background-surface": "light-dark(oklch(100% 0 0), rgb(216 227 255 / 0.07))",
    "--color-background-card": "light-dark(oklch(100% 0 0), rgb(216 227 255 / 0.07))",
    "--color-background-popover": "light-dark(oklch(96.5% 0.012 256), rgb(216 227 255 / 0.13))",
    "--color-background-muted": "light-dark(oklch(96.5% 0.012 256), rgb(216 227 255 / 0.13))",
    "--color-text-primary": "light-dark(oklch(21% 0.04 265), #ffffff)",
    "--color-text-secondary": "light-dark(oklch(37% 0.044 257), oklch(87% 0.028 262))",
    "--color-text-disabled": "light-dark(oklch(45% 0.043 257), oklch(70.4% 0.045 258))",
    "--color-text-accent": "light-dark(oklch(44% 0.125 224), oklch(89% 0.09 205))",
    "--color-icon-primary": "light-dark(oklch(21% 0.04 265), #ffffff)",
    "--color-icon-secondary": "light-dark(oklch(37% 0.044 257), oklch(87% 0.028 262))",
    "--color-icon-disabled": "light-dark(oklch(45% 0.043 257), oklch(70.4% 0.045 258))",
    "--color-icon-accent": "light-dark(oklch(44% 0.125 224), oklch(89% 0.09 205))",
    "--color-border": "light-dark(rgb(15 23 43 / 0.12), rgb(216 227 255 / 0.14))",
    "--color-border-emphasized": "light-dark(rgb(15 23 43 / 0.12), rgb(216 227 255 / 0.14))",
    "--color-success": "light-dark(oklch(69.6% 0.17 162.48), oklch(69.6% 0.17 162.48))",
    "--color-error": "light-dark(oklch(63.7% 0.234 25.3), oklch(63.7% 0.234 25.3))",
    "--color-warning": "light-dark(oklch(80% 0.15 78), oklch(80% 0.15 78))",
    "--color-border-blue": "light-dark(oklch(62.3% 0.214 259.815), oklch(74.6% 0.16 232.661))",
    "--color-icon-blue": "light-dark(oklch(62.3% 0.214 259.815), oklch(74.6% 0.16 232.661))",
    "--color-text-blue": "light-dark(oklch(47% 0.13 235), oklch(88% 0.07 232))",
    "--shadow-low": "none",
    "--shadow-med": "none",
    "--shadow-high": "none",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px"
  },

};
