/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx/theme.ts
 * Command: astryx theme build lib/astryx/theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/**
 * aernova theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { aernovaTheme } from './aernova';
 *   import './aernova.css';
 */
export const aernovaTheme = {
  name: 'aernova',
  __built: true,
  tokens: {
    "--duration-fast-min": "120ms",
    "--duration-fast": "160ms",
    "--duration-fast-max": "215ms",
    "--duration-medium-min": "165ms",
    "--duration-medium": "220ms",
    "--duration-medium-max": "295ms",
    "--duration-slow-min": "270ms",
    "--duration-slow": "360ms",
    "--duration-slow-max": "480ms",
    "--font-family-body": "\"var(--font-plex), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif\"",
    "--font-family-heading": "\"var(--font-plex), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif\"",
    "--color-accent": "light-dark(oklch(20% 0.012 264), oklch(97% 0.004 75))",
    "--color-on-accent": "light-dark(oklch(97.5% 0.004 260), oklch(14% 0.014 264))",
    "--color-background-body": "light-dark(oklch(97.5% 0.004 260), oklch(14% 0.014 264))",
    "--color-background-surface": "light-dark(oklch(100% 0 0), rgb(224 226 230 / 0.07))",
    "--color-background-card": "light-dark(oklch(100% 0 0), rgb(224 226 230 / 0.07))",
    "--color-background-popover": "light-dark(oklch(97% 0.006 260), rgb(224 226 230 / 0.13))",
    "--color-background-muted": "light-dark(oklch(97% 0.006 260), rgb(224 226 230 / 0.13))",
    "--color-text-primary": "light-dark(oklch(20% 0.012 264), oklch(97% 0.004 75))",
    "--color-text-secondary": "light-dark(oklch(36% 0.014 258), oklch(86% 0.01 260))",
    "--color-text-disabled": "light-dark(oklch(45% 0.014 258), oklch(69% 0.014 258))",
    "--color-text-accent": "light-dark(oklch(44% 0.125 224), oklch(89% 0.09 205))",
    "--color-icon-primary": "light-dark(oklch(20% 0.012 264), oklch(97% 0.004 75))",
    "--color-icon-secondary": "light-dark(oklch(36% 0.014 258), oklch(86% 0.01 260))",
    "--color-icon-disabled": "light-dark(oklch(45% 0.014 258), oklch(69% 0.014 258))",
    "--color-icon-accent": "light-dark(oklch(44% 0.125 224), oklch(89% 0.09 205))",
    "--color-border": "light-dark(rgb(22 24 28 / 0.12), rgb(224 226 230 / 0.14))",
    "--color-border-emphasized": "light-dark(rgb(22 24 28 / 0.12), rgb(224 226 230 / 0.14))",
    "--color-success": "light-dark(oklch(69.6% 0.17 162.48), oklch(69.6% 0.17 162.48))",
    "--color-on-success": "light-dark(oklch(14% 0.014 264), oklch(14% 0.014 264))",
    "--color-error": "light-dark(oklch(63.7% 0.234 25.3), oklch(63.7% 0.234 25.3))",
    "--color-on-error": "light-dark(oklch(14% 0.014 264), oklch(14% 0.014 264))",
    "--color-warning": "light-dark(oklch(80% 0.15 78), oklch(80% 0.15 78))",
    "--color-border-blue": "light-dark(oklch(62.3% 0.214 259.815), oklch(74.6% 0.16 232.661))",
    "--color-icon-blue": "light-dark(oklch(62.3% 0.214 259.815), oklch(74.6% 0.16 232.661))",
    "--color-text-blue": "light-dark(oklch(47% 0.13 235), oklch(88% 0.07 232))",
    "--shadow-low": "0px 1px 2px light-dark(rgb(10 15 20 / 0.10), rgb(10 15 20 / 0.35)), 0px 1px 1px light-dark(rgb(10 15 20 / 0.06), rgb(10 15 20 / 0.25))",
    "--shadow-med": "light-dark(0px 4px 16px rgb(10 15 20 / 0.12), 0px 4px 16px rgb(10 15 20 / 0.45))",
    "--shadow-high": "light-dark(0px 16px 40px rgb(10 15 20 / 0.18), 0px 16px 40px rgb(10 15 20 / 0.55))",
    "--radius-inner": "4px",
    "--radius-element": "6px",
    "--radius-container": "8px"
  },

};
