/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx/theme.ts
 * Command: astryx theme build lib/astryx/theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const aernovaTheme: DefinedTheme;
